# Generated by Django 5.1.2 on 2024-10-23 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_list_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
