# Generated by Django 5.1.2 on 2024-10-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_todo_list_created_at_alter_todo_list_finish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_list',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='todo_list',
            old_name='Title',
            new_name='title',
        ),
    ]
